alias fgr="grep -REIn --color=auto $*"
alias ls='ls --color=auto'
alias svndiff="svn diff | colordiff"
alias svri="svn revert -R $*"
alias pingu="ping google.com"
alias die="sudo poweroff"
alias bex="bundle exec $*"
alias fucking="sudo $*"
alias nomnomnom="rm -rf $*"
alias screenshot="flameshot $*"
